### ISSUE TITLE
Editor hangs on startup

### ISSUE THREAD

**Issue by SimonHarrison** [turanszkij/WickedEngine#10]
Hi turanszkij,

Your engine looks wicked!  Your demo videos are very impressive for a solo development and your code looks very good.  Awesome work.

I'm interested in trying out Wicked Engine but the editor seems to hang in LoadShaders due to a deadlock (it can't get a lock in wiResourceManager::get).

I've tried debug, release, 32 bit and 64 bit builds on two different PCs but with the same result on both the master branch and Vulkan branch running inside or outside on Visual Studio.

![image](https://user-images.githubusercontent.com/8501710/37859133-75c65ccc-2f4a-11e8-87f8-674804613658.png)

Am I doing something wrong or is this a potential bug?

Thanks for you help.

Cheers,

Simon

**Comment by turanszkij** [comment]
Hi Simon,

Thank you for your interest in this and for the report. This seems like a bug which most likely is caused by a shader loading error. For some reason the messagebox which would report the missing shader is failing to become visible recently. I will investigate this. By the way, did the whole solution compile for you without errors? Because the shader compilation is included in the Editor project build, if the project compiles properly it means that every shader should be available. Some hlsl shaders might fail to compile on earlier windows 10 builds. And the vulkan branch is not ready to use yet, however the master branch should work "out of the box".

Thanks again,
Janos

**Comment by turanszkij** [comment]
Hotfix available on master branch, the messagebox will now be displayed, does this solve the deadlock problem for you?

**Comment by SimonHarrison** [comment]
Wow, thanks for such a quick response!

Your fix resolves the problem and the dialog now shows.  The dialog reports that volumeLightPS.cso is not found.  I can't see a shader hlsl file for this, so perhaps it's missing from git?

I don't get any errors when building master and everything is working now thanks!

**Comment by turanszkij** [comment]
This was caused by a missing shader, because the shader was renamed but the engine code was still looking for the old name. Unfortunately, the old shader was still available on my PC so I hadn't run into the warning message. I resolved it now, thanks for the report! 👍
