### ISSUE TITLE
Modify the rotation center in the Editor

### ISSUE THREAD

**Issue by happydpc** [turanszkij/WickedEngine#124]
The camera_transform and camera_target are confusing, could you explain these two? It's hard to implement modify rotation center with these two. Maybe I misunderstand it, I just change the camera_target's translation vector.

**Comment by happydpc** [comment]
Rotate around the selected object will be perfect for the editor.

**Comment by turanszkij** [comment]
- camera_transform is the location of the camera itself. For FPS camera, the local transform is absolute in world space. For orbital camera, the local transform is relative to the camera_target (because it's parented).
- camera_target is the pivot of the camera, the center of rotation. It is only used for orbital camera, which rotates around a point in space while keeping a distance.

Basically, camera_target is the parent transform for the camera_transform, I hope that clears it up.

**Comment by happydpc** [comment]
Yes, that's very helpful. Thank you.
