### ISSUE TITLE
Duplicate function that will duplicate hierarchy

### ISSUE THREAD

**Issue by CaminoOnPc** [turanszkij/WickedEngine#184]
When the following code is used duplicate does not work

```
wiECS::Entity duplicate = wiScene::GetScene().Entity_Duplicate(cached->m_Entity);
if (duplicate)
{
    wiScene::GetScene().transforms.Create(duplicate);
    wiScene::TransformComponent* transform = wiScene::GetScene().transforms.GetComponent(duplicate);
    if (transform)
    {
        transform->RotateRollPitchYaw(XMFLOAT3(XMConvertToRadians(m_Rotation.x), XMConvertToRadians(m_Rotation.y), XMConvertToRadians(m_Rotation.z)));
        transform->Translate(XMFLOAT3(m_Position.x, m_Position.y, m_Position.z));
        transform->UpdateTransform();
    }
}
```

As @turanszkij described in discord

> Basically the Entity_Duplicate can't duplicate a complete hierarchy of entities, but only a single entity. I will think about whether it's feasible to have a duplicate that will retain the hierarchy.

I'm going to feature request issue here just in case

**Comment by turanszkij** [comment]
Correction: above code does work, but it doesn't do what you intended, since your duplicated entity is a parent of a hierarchy, but duplication only duplicates a single entity without hierarchy.

I did a first try to solve this but unfortunately ran into a problem that **I will need to think about more how to solve**. The problem is that even if I collect all entities part of the hierarchy and duplicate them, the duplicated hierarchy components still have the old parent references inside. They will need to be remapped somehow after duplication.

**Comment by turanszkij** [comment]
Ok, I figured it out. Now the Entity_Duplicate() will duplicate all of the hierarchy tree starting below the entity. I guess there is no reason to keep a duplicate function that doesn't retain hierarchy, so I modified the existing function. Feel free to reopen if you have any problems with it.

**Comment by CaminoOnPc** [comment]
Amazing, thanks
