### ISSUE TITLE
a sharp drop in the number of frames per second

### ISSUE THREAD

**Issue by Geniok** [turanszkij/WickedEngine#193]
When you rotate the camera, there is a sharp increase in memory allocation and a drawdown in the number of frames per second.
In this case, the distance to the object does not change, only a turn occurs.

![2](https://user-images.githubusercontent.com/3386000/100477737-53c04980-30fa-11eb-9511-1f3bb2e383d0.png)

![1](https://user-images.githubusercontent.com/3386000/100477749-59b62a80-30fa-11eb-9644-1e0f2fbc821f.png)

**Comment by Geniok** [comment]
Scene and script

[testScript.zip](https://github.com/turanszkij/WickedEngine/files/5609269/testScript.zip)

**Comment by Geniok** [comment]
![3](https://user-images.githubusercontent.com/3386000/100478549-92570380-30fc-11eb-97d0-63230d0ec301.png)

**Comment by turanszkij** [comment]
Hi, 
Thanks for attaching pictures and repro case. I tried to run the attached script, but it produces errors like:
```
[Lua Error] [string "..."]:82: [Lua Error] [string "-- Lua Third person camera and character cont..."]:402: attempt to index a nil value
[Lua Error] Line 69: Scale(Vector vector) argument is not a vector!
[Lua Error] Line 70: Rotate(Vector vectorRollPitchYaw) argument is not a vector!
```
Is there anything else I need to do? I haven't investigated the script deeply. 
If the errors appear to you too, please fix them beforehand. (check Visual Studio debug output, or backlog in the application by pressing HOME button)

**Comment by Geniok** [comment]
Ok, updated the script.
[fps.zip](https://github.com/turanszkij/WickedEngine/files/5610661/fps.zip)

**Comment by turanszkij** [comment]
Thanks. The slowness is caused by the intersection functions (**Pick(), SceneIntersectCapsule()**) with the **high poly Buddha model** (~1 million triangles). It is especially a problem because these intersection functions are called in loops several times per frame in this script (which is based on character controller script). It's not recommended to have high polygon count meshes participate in intersection tests.

The **workaround** would be to have a small polygon count version of that model that is not rendered, but only used for intersection tests. This can be achieved by setting a layer mask to the high poly buddha mesh that will not be included in intersection tests (for example the layer mask parameter in Pick() function). The low poly version can be set to non renderable and included in intersection testing.

The **long term solution** would be to implement hierarchy based primitive traversal for intersection functions with meshes, but that requires additional memory and precomputation, so not trivial to implement. The implementation of this is currently **not planned** in the short term.

**Comment by Geniok** [comment]
Yes, it looks like it is.
I will rewrite these functions according to your advice.
Thanks!

**Comment by turanszkij** [comment]
Feel free to reopen if you have any other problems.
