### ISSUE TITLE
Particle buffer index off by one?

### ISSUE THREAD

**Issue by mrdooz** [turanszkij/WickedEngine#205]
I was reading your particle system GPU implementation (it's very clear and easy to follow, so thank you very much!), and I think that when you index into the particle buffer in the particle simulator code, you're off by one (you should be using `newAliveIndex-1` and `deadIndex-1`, like you do in the emitter code.
https://github.com/turanszkij/WickedEngine/blob/ce84de103372e15dcafe242b1b3325e1ae94aa71/WickedEngine/emittedparticle_simulateCS.hlsl#L187

**Comment by turanszkij** [comment]
I think this is correct, the InterlockedAdd will return the previous value before the Add happened. This is good when incrementing and adding items to a list starting from an empty list. The dead list however is not incremented, but decremented and we can't use the previous value. Consider the case when everything is dead, so the dead list is full. The previous value before decrement will be the dead item count, however that is not a valid index into the dead list because it would refer to the element after the last.

**Comment by mrdooz** [comment]
Ah, thanks for the explanation! You saved me a bug in my implementation :)

**Comment by turanszkij** [comment]
No problem, good luck with your implementation! :)
