### ISSUE TITLE
Rectangle and disc area light problem

### ISSUE THREAD

**Issue by rextimmy** [turanszkij/WickedEngine#25]
Hey i noticed that both the rectangle and disc area lights display a line through the middle when you are perpendicular to them. If you strafe the camera left/right, the line moves with it. Only these two area lights seem to have the problem. See screenshots below:

[Rectangle Area light](https://imgur.com/5sZrjpM)
[Disc Area Light](https://imgur.com/GPNgguF)

**Comment by turanszkij** [comment]
Hi, thanks for reporting this. It should be fixed now in [commit](https://github.com/turanszkij/WickedEngine/commit/27392a3c4977cdd8b9c61ed74dc862213261db1b) 
This was an issue with ray tracing the light plane for specular reflection when the ray was parallel to the plane. With the fix, the specular will be faded out when approaching parallel direction. However, this is not physically correct way to do it. But none of these area light shaders are physically correct anyway, so that's okay. The directional, point and spot lights are physically based ones and are more optimized, so those should be used most of the time.
Feel free to close this one if you are happy with the resolution. :)

**Comment by rextimmy** [comment]
That was quick! ..Yes working sweet now. Will close the issue :)
