### ISSUE TITLE
How to use more than one  RenderPath3D to render ?

### ISSUE THREAD

**Issue by bitTalk1** [turanszkij/WickedEngine#308]
I add a RenderPath3D to EditorComponent , and add method call just like  internal renderPath , but can't render correctly.

A new camera , scene ,RenderPath3D   constructed in EditorComponent::TestCreatePath3D .

[Editor.zip](https://github.com/turanszkij/WickedEngine/files/7150622/Editor.zip)

**Comment by turanszkij** [comment]
What's the problem and what is the expectation? It seems to work for me as in I see something being rendered. If I don't set your custom camera to your new renderpath, it's rendered normally. Yout custom camera position is never modified, so it just sits in the center I think.

**Comment by bitTalk1** [comment]
I update my camera  using internal camera in  EditorComponent::Update:

mCamera1->TransformCamera(cameraWnd.camera_transform);
mCamera1->UpdateCamera();

**Comment by turanszkij** [comment]
In that case, I think the problem might be that since you create the camera inside the scene hierarchy, it's always gonna be updated from its transform component. The main camera probably shouldn't be part of the scene, but controlled by your custom code only. At least that's how I was doing it in my own code. Also, it's not safe to get a pointer to the camera component if it's in the scene and store it, because pointers in the scene can get invalidated whenever new entities/components are added. For things in the scene, the `Entity` handles can be used as persistent handles that will never change.

**Comment by bitTalk1** [comment]
thanks.
done it.

**Comment by bitTalk1** [comment]
got new problem:
how to  compose  my RenderPath3d with internal  ?
I compose them like this:
 	m3dPath1.Compose(cmd);
	renderPath->Compose(cmd);
in  EditorComponent::Compose;  

can't see my RenderPath3d's content .

**Comment by turanszkij** [comment]
I think the renderPath composes over your own m3dPath1.

**Comment by bitTalk1** [comment]
could you give me some guides to compose them ?

**Comment by turanszkij** [comment]
Depends on what you want, but with this:
m3dPath1.Compose(cmd);
renderPath->Compose(cmd);
The problem is that first you render your own, then the renderPath will be rendered on top of it. Maybe if you switch the order, your renderpath will be on top.
But if you want to render them side by side, you will have to write a custom Compose function that draws the two of them on different parts of the screen. You will need to chek out how the Compose works, it basically renders the final render target on to the screen with the wiImage::Draw()
