### ISSUE TITLE
SSAO and draw distance

### ISSUE THREAD

**Issue by jdswebb** [turanszkij/WickedEngine#31]
Hi,

I noticed that SSAO only seems to work well with a short view distance. Here is sponza with a draw distance of 500m:

![image](https://user-images.githubusercontent.com/5884019/62094130-eb4a2980-b273-11e9-9536-3363a9061376.png)

and again at 5000m:

![image](https://user-images.githubusercontent.com/5884019/62094068-b0e08c80-b273-11e9-821f-11d58c68d743.png)

At 5000m the result looks wrong - I'm curious if this is just an inherent limitation or something that could be improved/fixed?

Thanks

**Comment by turanszkij** [comment]
Hi, thanks for reporting! I didn't know about this. Might be because of reduced precision (16-bit) of the linear depth buffer. SSAO needs other quality and perf improvements too, maybe a complete rewrite.

**Comment by turanszkij** [comment]
It is fixed now

**Comment by jdswebb** [comment]
Thanks, I tried it out and it seems pretty good now up to far plane = 5k. After that it becomes stripy like this:

![image](https://user-images.githubusercontent.com/5884019/62729264-85993280-ba15-11e9-8fa6-8fa555077edc.png)

I appreciate I'm adjusting WE to allow more than 5k on the far plane - so if that's the intended limit then fine! 😃

**Comment by turanszkij** [comment]
Thanks again for testing, this is now a depth buffer precision problem. It won't be fixed, because for most cases, 16-bit linear depth buffer is enough and much better for performance. If you want such a large draw distance, you can fix it with changing one line (wiRenderer.h, line 19): 
`static const wiGraphics::FORMAT RTFormat_lineardepth = wiGraphics::FORMAT_R16_UNORM;`
change to this:
`static const wiGraphics::FORMAT RTFormat_lineardepth = wiGraphics::FORMAT_R32_FLOAT;`
Now the 16-bit precision works well up to ~10 000 units view distance

I just pushed an other quick fix for ssao too.
