### ISSUE TITLE
Advanced Decals (Decals with PBR and maybe parralax?)

### ISSUE THREAD

**Issue by megumumpkin** [turanszkij/WickedEngine#315]
Like the title said, so from what i've seen currently on the engine decals only modify the surface color, but not other PBR material properties, diffuse alpha will be used as the cutoff of the PBR layers, with parallax maybe we can create engravings in a mesh without the need to edit the model itself.
Well, this is like the decals i know in idtech7?

**Comment by turanszkij** [comment]
Hi, this is possible to do, just need to watch out not to make shaders slower. Since decals are applied in the object shaders, have to avoid putting much more code in there, especially parallax code that could be pretty large. Object shaders have the parallax compiled for specific variants because of this, but that will not be possible for decals, so the parallax code would need to be in every shader in that case..

**Comment by turanszkij** [comment]
Decals now support color, normal PBR surface properties and parallax occlusion mapping.
