### ISSUE TITLE
Crash on windows changing move_object.ua 

### ISSUE THREAD

**Issue by Ifelsethendo** [turanszkij/WickedEngine#377]
I changed these two lines
```
LoadModel("../models/cube.obj")
top_entity = scene.Entity_FindByName("Cube") --
```
Crash. I removed all other lines below that to see what would happen. Crash.
![Wicked_Archive_error](https://user-images.githubusercontent.com/93362020/147351691-edaab1e2-b29f-41b7-ae59-d3263cf65f6f.PNG)

I think at some point my computer rebooted to. Going to post this and test it again.

It dies on the LoadModel I tried a cube.glb as well and it crashed with the same or similar error, not sure what allt he numbers are.
Meanwhile the original Teapot script works.

**Comment by turanszkij** [comment]
You can not load obj or common model formats with `LoadModel` function, you can only load .wiscene format (the engine's native format). You can only load OBJ and GLTF/GLB in the editor. Because the scene was not loaded successfully, and you try to use it, you will likely crash because of some invalid pointer or something.
