### ISSUE TITLE
Demo sponza scene red light flickered in environment probe

### ISSUE THREAD

**Issue by Snowapril** [turanszkij/WickedEngine#399]
![output2](https://user-images.githubusercontent.com/24654975/156002751-35cc7a22-9c2f-457b-a3a3-511752eed726.gif)

### Reproduce revision
Branch : master
Commit id : 64888647b0a697a

### Reproduce environment
Selected Graphics API : Vulkan
CPU : AMD Ryzen 5 5600X
GPU : NVIDIA GTX 960
OS : Windows 11

### Description
If you take a look Environment probe, you may notice something flickering red light .
In sponza scene without any other additional settings, point light leakage occurred in certain camera direction.

**Comment by turanszkij** [comment]
I know about this, but I didn't think it's a very important issue. This happens because point light's render the scene into 6 cameras (6 directions), but only into those that are visible in the main camera. The environment probe is similar, it renders the scene in 6 directions, but it reuses shadow maps from main camera. It would be too complicated/expensive to have a separate set of shadow maps for every camera and every probe in the scene, so this is a compromise.

If this is really important to you, you can disable this optimization in the engine by removing this block in wiRenderer.cpp RenderMeshes() function ( https://github.com/turanszkij/WickedEngine/blob/master/WickedEngine/wiRenderer.cpp#L2575 ) :
```cpp
if (frusta != nullptr && !frusta[frustum_index].CheckBoxFast(instanceAABB))
{
	// In case multiple cameras were provided and no intersection detected with frustum, we don't add the instance for the face:
	continue;
}
```
This will disable point light shadow's "per face culling" and always render them in all directions. It will be most likely a minor performance impact.
But there are other culling behaviour for main camera, which can skip lights/shadows entirely depending on whole lights being visible, I don't recommend turning that off.

**Comment by Snowapril** [comment]
Ah.. I got it why it has happened. Then you mean that "Although this is not the desired behavior but fixing it leads to another problem (complicated/expensive result) so keeping it now" ?

**Comment by turanszkij** [comment]
Yes, for now it will remain like this. You can choose to apply my suggested workaround however if you want.
