### ISSUE TITLE
Area lights should be supported everywhere

### ISSUE THREAD

**Issue by antonyjones67** [turanszkij/WickedEngine#48]
Intel I7
Windows 10
64 bit 
Nvidia 1060 GTX
It is easy to see the problem, just add an area light to the top of the Cornellbox. Add a GIProbe. And turn on Global Illumination and Global Illumination Debug. Notice that the voxelization is really strange.

**Comment by turanszkij** [comment]
Hi, area lights are not implemented for voxel GI and path tracing yet. For now, you can add a mesh to the scene and set it to be emissive and that will work as area light (only in path tracing and voxel gi). Proper area light support for those should be added in the future though.

**Comment by turanszkij** [comment]
By the way, you don't have to put any probes for voxel GI

**Comment by antonyjones67** [comment]
Thank you! :)

**Comment by turanszkij** [comment]
Area lights should be unified to work everywhere consistently. Right now problematic areas are:
-Path tracing: Area light shadow rays need to be implemented by selecting random point on area light surface. There are at least 4 area light types which will need different algorithms to select these points. An other problematic area is the area light visualizers, they should be traced at primary rays first bounce only, otherwise they would contribute twice (punctual and stochastic).
-Voxel GI: Need to voxelize area light geometries.
-General performance: current area light implementation is producing rather heavy shaders. 
Right now this reamins a low priority feature request.

**Comment by turanszkij** [comment]
Area lights were removed some time ago
