### ISSUE TITLE
Shader refactor

### ISSUE THREAD

**Issue by amerkoleci** [turanszkij/WickedEngine#58]
Remove all shader specialization and keep only Shader with ShaderStage maybe.

What do you think?

**Comment by turanszkij** [comment]
I think this is a good idea, there is not much point to have a lot of different shader creation functions, and this will keep the graphics API wrapper simpler. 

The only place where it's important is the difference between graphics and compute shaders. I think instead of CreateXXXShader() functions on the device, there should be a CreateShader(), that also expects a SHADERSTAGE type as parameter. 

SHADERSTAGE parameter can be used there to differentiate by shader type, but it should also be a member of generic Shader class to be able to see it in the debugger and do asserts if for example the user tries to do a BindComputeShader() with a graphics shader.

Feel free to do it if you want and do a pull request.

**Comment by turanszkij** [comment]
Done
