### ISSUE TITLE
[Bug] GI on AMD does not seam correct

### ISSUE THREAD

**Issue by PlasmaDev5** [turanszkij/WickedEngine#596]
On my AMD GPU, Surfel GI and DDGI seam to render incorrectly. From what i can tell i need to turn the boost up to 3x before any bounce is visible

1X GI boost
![image](https://user-images.githubusercontent.com/3044415/203770338-2d1235e2-c8bf-46e8-8c63-d9b5bc2d1cd8.png)

10x GI boost
![image](https://user-images.githubusercontent.com/3044415/203770427-50f9b35c-c88f-4e80-bbb2-2e81a3bb84a9.png)

DDGI Debug
![image](https://user-images.githubusercontent.com/3044415/203770233-b9b4af34-e020-4770-8804-c7473d44a203.png)

Surfel GI Color Debug
![image](https://user-images.githubusercontent.com/3044415/203770566-03573480-2376-4d9b-9702-c39e71200749.png)

System Specs
[DxDiag.txt](https://github.com/turanszkij/WickedEngine/files/10083911/DxDiag.txt)

**Comment by turanszkij** [comment]
Yeah, sorry I don't have AMD GPU to test on. The GI in Sponza can be quite dark, I think this is because the materials and light intensity values. But The surfel color debug shouldn't be fully black, that seems like an issue for sure.

This is DDGI in Sponza for me in default camera position, GI-boost = 1: 
![image](https://user-images.githubusercontent.com/12954849/203845411-56cb7e3f-16e4-4d02-99ca-a2baac541db9.png)

Surfel GI color debug, GI-boost = 1: 
![image](https://user-images.githubusercontent.com/12954849/203845517-2425ad8d-ffc7-457a-a2f9-ba48dfc0d0e2.png)

 Are the results completely different for you in that camera angle and default settings?

**Comment by PlasmaDev5** [comment]
Yes the results are completely different. All settings are the default out of box setting. its like there is no light bounce from the sun
![image](https://user-images.githubusercontent.com/3044415/203849682-326d183e-3f00-459f-acda-1dde296abf49.png)

**Comment by turanszkij** [comment]
Hi, could you check if this commit fixes the issue for you: https://github.com/turanszkij/WickedEngine/commit/987421d435b7cc9d3218cf1761b014ce5db2cfe1
I could reproduce something similar with the updated shader compiler, and I fixed that (but I can't confirm that it is the same issue what happens on AMD).

**Comment by PlasmaDev5** [comment]
sorry for the delay didnt notice the reply. Does not look to have effected issues on AMD

**Comment by turanszkij** [comment]
I have tested these on AMD RX6650 and the GI looks to be working correctly there.
