### ISSUE TITLE
VXGI doesn't take sky into account

### ISSUE THREAD

**Issue by trsh** [turanszkij/WickedEngine#632]
Voxel gi

![2023-01-28_180340](https://user-images.githubusercontent.com/3727523/215276600-654426f6-e16c-4564-b821-560d9c2c7476.png)

ddgi

![2023-01-28_180738](https://user-images.githubusercontent.com/3727523/215276813-a73fe411-cf48-48e6-b01f-b86e46f3ca62.png)

**Comment by turanszkij** [comment]
VXGI has fallback to environment probe. The Sponza scene has a static environment probe, so if you update the sky but not the envprobe, then it will look like the sky change has no effect. To fix this, you can delete the environment probe or set it to real time. But it is not possible currently to reproduce the same quality of sky light in VXGI as DDGI.

**Comment by trsh** [comment]
@turanszkij interesting. I tried to delete the env probe or set it to real Realtime. But still sky had no effect on it when changing exposure. Even made some dark place blue, where it should be not.

**Comment by trsh** [comment]
Actually, when deleting env probe, the sky exposure actually has some effect. But generally it all looks a bit weird. Why In can't be like with DDGI? Miss rays/cones go to sky?

**Comment by turanszkij** [comment]
The missing rays do sample the sky in vxgi, but the miss in vxgi is not a binary yes/no, it is accumulating alpha by going through mip levels, and a miss occurs when ray step distance reached max value or it exists last clipmap. But usually the rays are terminated because enough alpha opacity was accumulated in diffuse - because the diffuse cones are extremely wide and going up mip levels very fast.

**Comment by turanszkij** [comment]
So I just want to say that currently I don't have a good solution to get more precision.

**Comment by trsh** [comment]
Ok, tnx
