### ISSUE TITLE
Cache graphics objects

### ISSUE THREAD

**Issue by amerkoleci** [turanszkij/WickedEngine#66]
Currently CreateBlendState, CreateRasterizerState etc calls native side and creates new instances every time, cache maybe and avoid creation same state or maybe keep only description as part of PipelineState and manage dx11 side only

**Comment by turanszkij** [comment]
What are you trying to accomplish with it? Usually there are more pipeline states than blend states, rasterizer, etc, so it makes sense to only reference them by the pipeline state with a pointer instead of storing their description. 

The current system combines both the native way of creating states in dx11 and dx12/vulkan. I feel like caching system would unnecessarily complicate the device.

**Comment by amerkoleci** [comment]
The cache would be on dx11 side only, others will use the descriptions, if I don't recall wrong CreateBlendState, CreateRasterizerState etc are cached on dx11 side, the ID3DDevice11 won't create more objects with same description

**Comment by turanszkij** [comment]
The d3d11 device probably does cache a lot of things. So why would you cache it yourself? The caching is done for dx12 and vulkan wrappers where it caches PipelineStateDesc (blendstate, rasterizer, shaders, etc.) + renderpass.

**Comment by turanszkij** [comment]
I might be missing your point. If you implement this and it reduces memory or improves performance, I'd be of course happy to accept it.
