### ISSUE TITLE
simulated Rigidbody physics mesh not translated with model transform

### ISSUE THREAD

**Issue by AnthonyPython** [turanszkij/WickedEngine#709]
When I tried to use the transform as input where the new loaded model should be, the rigidbody phys mesh is at it's original location.

wicked engine steam, version: 0.71.241

replication: move the cube model other than where originally . hit the play on the script.

[destruct.zip](https://github.com/turanszkij/WickedEngine/files/12098195/destruct.zip)

https://github.com/turanszkij/WickedEngine/assets/6700701/bae7a526-0d03-40e7-bf18-2c903e23b54f

**Comment by turanszkij** [comment]
This should be fixed by the above linked commit. The problem was that this rigid body is attached to a parent, and its physics was simulated in local space which is fine only if they don't have parent. I switched rigid bodies to be created in world space, but in this case they need to be detached from their parent, which will be done automatically.

**Comment by AnthonyPython** [comment]
I see, thanks turan
