### ISSUE TITLE
Upsampling accumulated volumetric light

### ISSUE THREAD

**Issue by jdswebb** [turanszkij/WickedEngine#88]
The light volumetrics give a pixelating effect when composited due to being rendered at 1/4 resolution. Upsampling based on depth can largely fix this.

I tried out the upsampling implementation from https://github.com/SlightlyMad/VolumetricLights and the results were very good for negligible performance impact.

**Comment by turanszkij** [comment]
Yes, this is a good idea, I was planning on doing something to avoid pixelation, but haven't got around to it. If you'd like to add this, feel free to :)

**Comment by turanszkij** [comment]
Btw I've tried it, works nice and will add it soon after some more testing

**Comment by jdswebb** [comment]
Oh nice, thanks, you beat me to it then :)

I had a PS implementation done based on the one I'd linked but have been working on a CS version to be more in-keeping with how you're doing things in WE now.

**Comment by turanszkij** [comment]
I have the CS implementation, but PS might be better for this specifically, because then don't have to store the full res upsampled result texture, just draw on top of the scene in the same pass.

**Comment by jdswebb** [comment]
Does it not work to manually do the additive blending in the CS rather than using PS with blend modes? That's what I was planning to do but perhaps I'm missing something or that's just a bad thing to do.

**Comment by turanszkij** [comment]
It can complicate things, because I'm using R11G11B10_FLOAT format, and some GPU don't support it for UAV loads. Which sucks and have to do workarounds, which I avoid where possible. An other reason is compositing the volumetrics on the scene is in the middle of a big render pass and it would be good not to break it with a compute shader. But I'll keep the compute shader because it will work well with upsampling SSAO or SSR which are not composited in the same way.

**Comment by jdswebb** [comment]
Makes sense, thanks for explaining!
